apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
    orleans/serviceId: {{ .Values.orleans.serviceId }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      orleans/serviceId: {{ .Values.orleans.serviceId }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        orleans/serviceId: {{ .Values.orleans.serviceId }}
        orleans/clusterId: {{ .Values.orleans.clusterId }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationGracePeriodSeconds: 180
          ports:
            - name: gateway
              containerPort: {{ .Values.orleans.gatewayPort }}
              protocol: TCP              
            - name:   
              containerPort: {{ .Values.orleans.siloPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: OpenMatchFrontEnd__Address
              value: {{ .Values.openmatch.frontend.address | quote }}
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "120"
            - name: Orleans__Clustering__Redis__ConnectionString
              value: {{ .Values.orleans.redis.connectionString | quote }}
