apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: {{ include "simple-game-server.fullname" . }}
  labels:
    {{- include "simple-game-server.labels" . | nindent 4 }}
spec:
  fleetName: {{ include "simple-game-server.fullname" . }}
  policy:
    type: Buffer
    buffer:
      bufferSize: {{ .Values.autoscaler.bufferSize }}
      minReplicas: {{ .Values.autoscaler.minReplicas }}
      maxReplicas: {{ .Values.autoscaler.maxReplicas }} 