apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.fleet.replicas }}
  template:
    spec:
      ports:
        - name: udp
          portPolicy: Dynamic
          containerPort: 7654
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              env:
                {{- toYaml .Values.env | nindent 16 }}
              {{- with .Values.ports }}
              ports:
                {{- toYaml . | nindent 16 }}
              {{- end }} 