apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: {{ .Chart.Name }}-autoscaler
spec:
  fleetName: {{ .Chart.Name }}
  policy:
    type: Buffer
    buffer:
      bufferSize: {{ .Values.autoscaler.bufferSize }}
      minReplicas: {{ .Values.autoscaler.minReplicas }}
      maxReplicas: {{ .Values.autoscaler.maxReplicas }} 