namespace: demo-game
replicaCount: 1

image:
  repository: gg-demo-backend
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

orleans:
  serviceId: demo-game-backend
  clusterId: dev 
  gatewayPort: 30000
  siloPort: 11111
openmatch:  
  frontend:
    address: "http://open-match-frontend.open-match.svc.cluster.local:51504" 