namespace: demo-game
replicaCount: 1

image:
  repository: gg-demo-function
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

openmatch:
  query:
    address: "http://open-match-query.open-match.svc.cluster.local:50503" 