replicaCount: 1

image:
  repository: redis
  tag: 7.2.4
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  size: 1Gi 