replicaCount: 1

image:
  repository: redis
  tag: 7.2.4
  pullPolicy: IfNotPresent

auth:
  password: "aBu123!v@lg"  # Change this to a secure password

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  size: 1Gi 