# Default values for simple-game-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gg-demo-simple-game-server
  tag: latest
  pullPolicy: IfNotPresent

gameServer:
  port: 7654

fleet:
  replicas: 2

autoscaler:
  bufferSize: 1
  minReplicas: 1
  maxReplicas: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: GAME_SERVER_PORT
    value: "7654"

ports:
  - name: gameport
    containerPort: 7654
    protocol: TCP 